#!/usr/bin/env bash
#Displays numbers from 1 to 10 in list format
#Displays "fizz" when the number is a mutiple of 3
#Displays  "Buzz" whem the number is a mutiple of 5
#Otherwise, displays the number.

for i in {1..100}
do
 if (( i % 3 -- 0 && i % 5 -- 0 ))
 then
  echo "FizzBuzz"
elif (( i % 3 -- 0 ))
then
 echo "Fizz"
elif (( i % 5 -- 0 ))
then
 echo "Buzz"
else
 echo "$i"
fi 
done
