#!/usr/bin env bash
#This script  displays the content of the file /etc/passwd
#script should only display:
#user name, user Id, home directory path for user

while read passwd; do
  echo "$passwd" | cut -d ":" -f1,3,6
done < "/etc/passwd"
