#!/usr/bin/env bash
# This script displays Best School 10 times with 9 iteration says Hi.

count=0
while [ $count -lt 10 ]
do	
if [ $count -eq 8 ]
then 
  echo "Best School Hi"
else
  echo 'Best School"
fi
(( count++ ))
done
