#!/usr/bin/env bash
# This script displays:

#The content of the current directory
#In a list format
#Whhere only the name after the first dash is dispalyed

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
