#!/usr/bin/env bash
#Bash script that gives you information abotu the school files

if [ -e "school" ]
then
  echo "school file exists"
if [ -s "school " ]
then
  echo "school file is not empty"
else
  echo "school file is emmpty"
fi

if [ -f "school" ]
then
echo "school is a regular file"
fi
else
  echo "school file does not exist"
fi
